# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36eb31eec9ae30e86c789618a815c1c485ca9d662bb5cb4f28f9b3b2f7e7b5438d4ffa0c149dab1e27960f8b5007b03efae1493ab34f9ff6c42fd3644976b7b1

test:
  secret_key_base: c5d923942e45c28f48a92165f683d37bfd11ef783c9beb26fa376d4aa68191ae413dbbdba0ab4d6ad20b054b5e2f84d927cf5de94b261d6c7c4d6c369f526d27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
